version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  terraform: circleci/terraform@3.2.1

jobs:
  build-push:
    parameters:
      workspace:
        type: string
      tf_state_bucket_name:
        type: string
      tf_state_key_path:
        type: string
    environment:
      AWS_REGION: ap-southeast-2
      AWS_ACCOUNT_ID: 058264290985
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/CircleCI_OIDC"
      - terraform/validate:
          path: modules/oidc_setup
      - terraform/fmt:
          path: modules/oidc_setup
      - terraform/plan:
          path: modules/oidc_setup
    working_directory: ~/lh-accela/
  deploy-stg:
    docker:
      - image: cimg/aws:2022.06
    steps:
      - run: echo "Deploy to stg"
      - terraform/plan:
          path: modules/oidc_setup
          backend: true
          backend_config:
           "bucket=<<parameters.tf_state_bucket_name>>, \
           key=<<parameters.tf_state_key_path>>, \
           region=us-east-1"
      - terraform/apply:
          path: modules/oidc_setup
          backend: true
          backend_config:
           "bucket=<<parameters.tf_state_bucket_name>>, \
           key=<<parameters.tf_state_key_path>>, \
           region=us-east-1"
workflows:
  core_infra:
    jobs:
      - build-push:
          workspace: "default"
          tf_state_bucket_name: "aops-edp-artefacts"
          tf_state_key_path: "oidc_setup/terraform.tfstate"