version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1
  aws-ecr: circleci/aws-ecr@9.0.1

jobs:
  build-push:
    environment:
      AWS_REGION: ap-southeast-2
      AWS_ACCOUNT_ID: 058264290985
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/CircleCI_OIDC"
      - aws-ecr/ecr_login:
          account_id: ${AWS_ACCOUNT_ID}
      - aws-ecr/build_image:
          push_image: false
workflows:
  docker:
    jobs:
      - build-push