version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  terraform: circleci/terraform@3.2.1

jobs:
  build-push:
    parameters:
      workspace:
        type: string
    environment:
      AWS_REGION: ap-southeast-2
      AWS_ACCOUNT_ID: 058264290985
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout
      - run: pwd
      - aws-cli/setup:
          role_arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/CircleCI_OIDC"
      - terraform/init:
          path: ~/lh-accela/modules/oidc_setup
      - terraform/validate:
          path: ~/lh-accela/modules/oidc_setup
      - terraform/fmt:
          path: ~/lh-accela/modules/oidc_setup
      - terraform/plan:
          path: ~/lh-accela/modules/oidc_setup
    working_directory: ~/lh-accela/modules/oidc_setup

workflows:
  core_infra:
    jobs:
      - build-push:
          workspace: "default"