version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  terraform: circleci/terraform@3.2.1

jobs:
  build-push:
    environment:
      AWS_REGION: ap-southeast-2
      AWS_ACCOUNT_ID: 058264290985
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/CircleCI_OIDC"
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/fmt:
          path: .
      - terraform/plan:
          path: .
      - terraform/apply:
          path: .
      - terraform/destroy:
          path: .
    working_directory: ~/base_infra

workflows:
  docker:
    jobs:
      - build-push